### ISSUE TITLE
How to build the plant_reader?

### ISSUE THREAD

**Issue by hmorkemo** [Djebouh/ble_reader#1]
Hi.
I like the plant_reader project, and would like to implement it/contribute to it.
But I need some help getting started.
When you say "Compile & upload on your ISP32", it seems simple, but it wasn't. Could you provide some more detailed steps?
(I'm fairly experienced with both VS 2019 and VS Code.)

**Comment by Djebouh** [comment]
Hello, did you install [platformio IDE](https://platformio.org/platformio-ide) in vs code? 
Then, you should have the ability to build and upload the project.

**Comment by hmorkemo** [comment]
I installed platformio IDE, and I can compile, but I get a lot of warnings for redefining constants, and one error:  #include <esp_gatts_api.h>
compilation terminated.
*** [.pio\build\esp32dev\esp-idf\src\BLEDescriptor.cpp.o] Error 1
I guess this has to do with missing espidf. Where do I fetch the right one (there is a lot of them...)?

**Comment by Djebouh** [comment]
Indeed, I did not use the project for some time and with the last platformio update it now fails, I will have a look, sorry for this issue.

**Comment by Djebouh** [comment]
It indeed works with a previous version of the platform.
The retrofit to Espressif 32 @ 1.11.2 brings framework-espidf @ ~3.30300.0.
With this set-up, it works. I will check later to understand the compatibility breaks
